<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="TTF-BLR-SANTOSHKOUJALAGI" name="com.tetherfi.test.UserRoleMappingCreateTest" tests="22" failures="0" timestamp="2021-12-17T02:54:22 IST" time="804.286" errors="4">
  <testcase name="VerifyAddCancelButton" time="23.957" classname="com.tetherfi.test.UserRoleMappingCreateTest"/>
  <testcase name="VerifyAddRecordwithoutFirstName" time="35.073" classname="com.tetherfi.test.UserRoleMappingCreateTest"/>
  <testcase name="VerifyAddRecordWithoutLastName" time="31.259" classname="com.tetherfi.test.UserRoleMappingCreateTest"/>
  <testcase name="VerifyAddRecordWithoutLanId" time="30.721" classname="com.tetherfi.test.UserRoleMappingCreateTest"/>
  <testcase name="VerifyAddRecordWithoutPBXID" time="33.229" classname="com.tetherfi.test.UserRoleMappingCreateTest"/>
  <testcase name="VerifyAddRecordWithoutAgentID" time="30.826" classname="com.tetherfi.test.UserRoleMappingCreateTest"/>
  <testcase name="VerifyAddRecordWithoutOrgUnitANDProfileAndSupervisor" time="29.257" classname="com.tetherfi.test.UserRoleMappingCreateTest"/>
  <testcase name="VerifyAddRecordWithoutProfile" time="31.184" classname="com.tetherfi.test.UserRoleMappingCreateTest"/>
  <testcase name="VerifyAddRecordWithoutSupervisor" time="37.281" classname="com.tetherfi.test.UserRoleMappingCreateTest"/>
  <testcase name="VerifyAddRecordWithoutRole" time="33.757" classname="com.tetherfi.test.UserRoleMappingCreateTest"/>
  <testcase name="AddRevertRecord" time="37.430" classname="com.tetherfi.test.UserRoleMappingCreateTest"/>
  <testcase name="VerifyRevertForAddNewRecord" time="33.919" classname="com.tetherfi.test.UserRoleMappingCreateTest"/>
  <testcase name="VerifyApprovedDataSectionWithoutApproval" time="22.603" classname="com.tetherfi.test.UserRoleMappingCreateTest"/>
  <testcase name="VerifyAuditTrailReportForRevert" time="57.497" classname="com.tetherfi.test.UserRoleMappingCreateTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.tetherfi.pages.OCMReportsPage.verifyUserRoleMappingCreate(OCMReportsPage.java:7556)
at com.tetherfi.test.UserRoleMappingCreateTest.VerifyAuditTrailReportForRevert(UserRoleMappingCreateTest.java:205)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- VerifyAuditTrailReportForRevert -->
  <testcase name="AddRejectRecord" time="37.525" classname="com.tetherfi.test.UserRoleMappingCreateTest"/>
  <testcase name="VerifySendForApprovalForAddNewRecord" time="60.367" classname="com.tetherfi.test.UserRoleMappingCreateTest"/>
  <testcase name="RejectforAddNewNewUserRoleMappingRecord" time="35.828" classname="com.tetherfi.test.UserRoleMappingCreateTest"/>
  <testcase name="VerifyAuditTrailReportForReject" time="47.647" classname="com.tetherfi.test.UserRoleMappingCreateTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.tetherfi.pages.OCMReportsPage.verifyUserRoleMappingCreate(OCMReportsPage.java:7556)
at com.tetherfi.test.UserRoleMappingCreateTest.VerifyAuditTrailReportForReject(UserRoleMappingCreateTest.java:247)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- VerifyAuditTrailReportForReject -->
  <testcase name="AddNewNewUserRoleMappingRecord" time="41.476" classname="com.tetherfi.test.UserRoleMappingCreateTest"/>
  <testcase name="VerifyAuditTrailReportForCreate" time="48.178" classname="com.tetherfi.test.UserRoleMappingCreateTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.tetherfi.pages.OCMReportsPage.verifyUserRoleMappingCreate(OCMReportsPage.java:7556)
at com.tetherfi.test.UserRoleMappingCreateTest.VerifyAuditTrailReportForCreate(UserRoleMappingCreateTest.java:280)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- VerifyAuditTrailReportForCreate -->
  <testcase name="VerifyAuditTrailDataForAddNewNewUserRoleMappingRecord" time="26.627" classname="com.tetherfi.test.UserRoleMappingCreateTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.tetherfi.pages.NewUserRoleMappingPage.verifyNewValues(NewUserRoleMappingPage.java:1423)
at com.tetherfi.pages.NewUserRoleMappingPage.verifyAuditTrail(NewUserRoleMappingPage.java:1405)
at com.tetherfi.test.UserRoleMappingCreateTest.VerifyAuditTrailDataForAddNewNewUserRoleMappingRecord(UserRoleMappingCreateTest.java:290)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- VerifyAuditTrailDataForAddNewNewUserRoleMappingRecord -->
  <testcase name="AddDuplicateRecord" time="38.645" classname="com.tetherfi.test.UserRoleMappingCreateTest"/>
</testsuite> <!-- com.tetherfi.test.UserRoleMappingCreateTest -->
