<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="TTF-BLR-SANTOSHKOUJALAGI" name="com.tetherfi.test.UserOnBoardingCountryLevelUserCreateTest" tests="15" failures="1" timestamp="2021-12-02T22:47:51 IST" time="657.820" errors="1">
  <testcase name="VerifyAddRevertRecord" time="51.551" classname="com.tetherfi.test.UserOnBoardingCountryLevelUserCreateTest"/>
  <testcase name="VerifyRevertForAddNewRecord" time="39.626" classname="com.tetherfi.test.UserOnBoardingCountryLevelUserCreateTest"/>
  <testcase name="VerifyAuditTrailReportForRevert" time="52.604" classname="com.tetherfi.test.UserOnBoardingCountryLevelUserCreateTest"/>
  <testcase name="AddRejectRecord" time="51.529" classname="com.tetherfi.test.UserOnBoardingCountryLevelUserCreateTest"/>
  <testcase name="VerifySendForApprovalForAddNewUserOnBoardingRecord" time="35.344" classname="com.tetherfi.test.UserOnBoardingCountryLevelUserCreateTest"/>
  <testcase name="RejectForAddNewUserOnBoardingRecord" time="30.291" classname="com.tetherfi.test.UserOnBoardingCountryLevelUserCreateTest"/>
  <testcase name="VerifyAuditTrailReportForReject" time="55.309" classname="com.tetherfi.test.UserOnBoardingCountryLevelUserCreateTest"/>
  <testcase name="AddNewUserOnBoardingRecord" time="53.103" classname="com.tetherfi.test.UserOnBoardingCountryLevelUserCreateTest"/>
  <testcase name="VerifyAuditTrailReportForCreate" time="48.755" classname="com.tetherfi.test.UserOnBoardingCountryLevelUserCreateTest"/>
  <testcase name="VerifyAuditTrailDataForAddNewUserOnBoardingRecord" time="28.779" classname="com.tetherfi.test.UserOnBoardingCountryLevelUserCreateTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.tetherfi.pages.UserOnBoardingPage.verifyNewValues(UserOnBoardingPage.java:1818)
at com.tetherfi.pages.UserOnBoardingPage.verifyAuditTrail(UserOnBoardingPage.java:1801)
at com.tetherfi.test.UserOnBoardingCountryLevelUserCreateTest.VerifyAuditTrailDataForAddNewUserOnBoardingRecord(UserOnBoardingCountryLevelUserCreateTest.java:175)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- VerifyAuditTrailDataForAddNewUserOnBoardingRecord -->
  <testcase name="VerifySendForApprovalForAddNewUserOnBoarding" time="34.707" classname="com.tetherfi.test.UserOnBoardingCountryLevelUserCreateTest"/>
  <testcase name="VerifyAuditTrailReportForSendForApproval" time="44.666" classname="com.tetherfi.test.UserOnBoardingCountryLevelUserCreateTest"/>
  <testcase name="ApproveforAddNewUserOnBoardingRecord" time="37.136" classname="com.tetherfi.test.UserOnBoardingCountryLevelUserCreateTest"/>
  <testcase name="VerifyAuditTrailReportForApprove" time="44.084" classname="com.tetherfi.test.UserOnBoardingCountryLevelUserCreateTest"/>
  <testcase name="AddDuplicateUserOnBoardingRecord" time="50.336" classname="com.tetherfi.test.UserOnBoardingCountryLevelUserCreateTest">
    <failure type="java.lang.AssertionError" message="Record Creation Assertion failed expected [Record Creation Failed, Already Exist] but found [Agent ID is already taken, Please provide Unique Agent ID]">
      <![CDATA[java.lang.AssertionError: Record Creation Assertion failed expected [Record Creation Failed, Already Exist] but found [Agent ID is already taken, Please provide Unique Agent ID]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.tetherfi.test.UserOnBoardingCountryLevelUserCreateTest.AddDuplicateUserOnBoardingRecord(UserOnBoardingCountryLevelUserCreateTest.java:233)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AddDuplicateUserOnBoardingRecord -->
</testsuite> <!-- com.tetherfi.test.UserOnBoardingCountryLevelUserCreateTest -->
