<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="admin" failures="0" tests="6" name="com.tetherfi.test.ivr.IntroMessageAnnouncementCreateTest" time="4.702" errors="1" timestamp="14 May 2019 06:20:39 GMT" skipped="5">
  <testcase classname="com.tetherfi.test.ivr.IntroMessageAnnouncementCreateTest" name="NavigateToIntroMessageAnnouncementPage" time="4.702">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.tetherfi.test.ivr.IntroMessageAnnouncementCreateTest.NavigateToIntroMessageAnnouncementPage(IntroMessageAnnouncementCreateTest.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- NavigateToIntroMessageAnnouncementPage -->
  <testcase classname="com.tetherfi.test.ivr.IntroMessageAnnouncementCreateTest" name="ApproveforAddNewIntroMessageAnnouncementRecord" time="0.000">
    <skipped/>
  </testcase> <!-- ApproveforAddNewIntroMessageAnnouncementRecord -->
  <testcase classname="com.tetherfi.test.ivr.IntroMessageAnnouncementCreateTest" name="VerifyAuditTrailReportForApprove" time="0.000">
    <skipped/>
  </testcase> <!-- VerifyAuditTrailReportForApprove -->
  <testcase classname="com.tetherfi.test.ivr.IntroMessageAnnouncementCreateTest" name="VerifyAuditTrailDataForAddNewIntroMessageAnnouncementRecord" time="0.000">
    <skipped/>
  </testcase> <!-- VerifyAuditTrailDataForAddNewIntroMessageAnnouncementRecord -->
  <testcase classname="com.tetherfi.test.ivr.IntroMessageAnnouncementCreateTest" name="AddNewIntroMessageAnnouncementRecord" time="0.000">
    <skipped/>
  </testcase> <!-- AddNewIntroMessageAnnouncementRecord -->
  <testcase classname="com.tetherfi.test.ivr.IntroMessageAnnouncementCreateTest" name="VerifyTaskCompleteActionForAddNewIntroMessageAnnouncementRecord" time="0.000">
    <skipped/>
  </testcase> <!-- VerifyTaskCompleteActionForAddNewIntroMessageAnnouncementRecord -->
</testsuite> <!-- com.tetherfi.test.ivr.IntroMessageAnnouncementCreateTest -->
