<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-05-27T12:13:11 IST" name="Default suite" finished-at="2020-05-27T12:15:11 IST" duration-ms="120327">
    <groups>
    </groups>
    <test started-at="2020-05-27T12:13:11 IST" name="Default test" finished-at="2020-05-27T12:15:11 IST" duration-ms="120327">
      <class name="com.tetherfi.test.reports.AgentHistoricalReportTest">
        <test-method is-config="true" signature="openApplication()[pri:0, instance:com.tetherfi.test.reports.AgentHistoricalReportTest@695c938d]" started-at="2020-05-27T12:13:11 IST" name="openApplication" finished-at="2020-05-27T12:13:33 IST" duration-ms="21924" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method is-config="true" signature="startTestCase(java.lang.reflect.Method)[pri:0, instance:com.tetherfi.test.reports.AgentHistoricalReportTest@695c938d]" started-at="2020-05-27T12:13:33 IST" name="startTestCase" finished-at="2020-05-27T12:13:33 IST" duration-ms="3" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.tetherfi.test.reports.AgentHistoricalReportTest.database() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="NavigateToOcmReportsPage()[pri:0, instance:com.tetherfi.test.reports.AgentHistoricalReportTest@695c938d]" started-at="2020-05-27T12:13:33 IST" name="NavigateToOcmReportsPage" finished-at="2020-05-27T12:13:35 IST" duration-ms="2246" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NavigateToOcmReportsPage -->
        <test-method signature="database()[pri:59, instance:com.tetherfi.test.reports.AgentHistoricalReportTest@695c938d]" started-at="2020-05-27T12:13:35 IST" name="database" description="To verify report data against DB" finished-at="2020-05-27T12:15:02 IST" duration-ms="86829" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Main Report Data Mismatch did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Main Report Data Mismatch did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.tetherfi.test.reports.AgentHistoricalReportTest.database(AgentHistoricalReportTest.java:756)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- database -->
        <test-method is-config="true" signature="afterEachMethod(java.lang.reflect.Method)[pri:0, instance:com.tetherfi.test.reports.AgentHistoricalReportTest@695c938d]" started-at="2020-05-27T12:15:02 IST" name="afterEachMethod" finished-at="2020-05-27T12:15:06 IST" duration-ms="3778" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.tetherfi.test.reports.AgentHistoricalReportTest.database() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterEachMethod -->
        <test-method is-config="true" signature="endTestCase(java.lang.reflect.Method)[pri:0, instance:com.tetherfi.test.reports.AgentHistoricalReportTest@695c938d]" started-at="2020-05-27T12:15:06 IST" name="endTestCase" finished-at="2020-05-27T12:15:06 IST" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.tetherfi.test.reports.AgentHistoricalReportTest.database() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTestCase -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tetherfi.test.reports.AgentHistoricalReportTest@695c938d]" started-at="2020-05-27T12:15:06 IST" name="tearDown" finished-at="2020-05-27T12:15:11 IST" duration-ms="5450" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tetherfi.test.reports.AgentHistoricalReportTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
